import Icon from "../Icon";
import {formatCurrency} from "../../utils/calculateSaleTotals";
function TotalsPanel({totals,discountType,discountValue,discountsEnabled,taxLabel,onDiscountType,onDiscountValue}){
 return <section className="border-t border-slate-100 bg-white p-5">
  <div className="flex items-start justify-between gap-3"><div><h4 className="text-sm font-extrabold text-slate-900">Order summary</h4><p className="mt-1 text-[10px] text-slate-400">{taxLabel}. Backend totals remain authoritative.</p></div><span className="grid size-9 place-items-center rounded-xl bg-blue-50 text-blue-700"><Icon name="sales" className="size-4"/></span></div>
  {discountsEnabled&&<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><p className="mb-2 text-[9px] font-extrabold uppercase tracking-[0.12em] text-slate-400">Sale discount</p><div className="grid grid-cols-[138px_1fr] gap-2"><select className="min-h-10 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700" value={discountType} onChange={e=>onDiscountType(e.target.value)} aria-label="Discount type"><option value="none">No discount</option><option value="fixed">Fixed discount</option><option value="percentage">Percentage</option></select><input disabled={discountType==="none"} className="min-h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm font-bold disabled:bg-slate-100" type="number" min="0" max={discountType==="percentage"?"100":undefined} step="0.01" value={discountValue} onChange={e=>onDiscountValue(e.target.value)} aria-label="Discount value"/></div></div>}
  <dl className="mt-4 space-y-2.5 text-xs"><div className="flex justify-between text-slate-500"><dt>Subtotal</dt><dd className="font-bold text-slate-800">{formatCurrency(totals.subtotal)}</dd></div>{discountsEnabled&&<div className="flex justify-between text-slate-500"><dt>Discount</dt><dd className="font-bold text-emerald-600">- {formatCurrency(totals.discount)}</dd></div>}<div className="flex justify-between text-slate-500"><dt>{taxLabel}</dt><dd className="font-bold text-slate-700">{formatCurrency(totals.tax)}</dd></div></dl>
  <div className="mt-4 flex items-center justify-between rounded-xl border border-blue-100 bg-blue-50 px-4 py-4"><span><small className="block text-[9px] font-extrabold uppercase tracking-[0.14em] text-blue-500">Amount payable</small><strong className="mt-1 block text-sm text-slate-800">Grand total</strong></span><strong className="text-xl font-extrabold tracking-tight text-blue-700">{formatCurrency(totals.grandTotal)}</strong></div>
 </section>;
}export default TotalsPanel;
