import {
  AlertTriangle, ArrowRight, Award, BadgeAlert, BadgeCheck, Banknote, Barcode, Boxes,
  CalendarX, ChartNoAxesCombined, Check, ChevronDown, ChevronLeft, ChevronRight,
  ChevronsLeft, ChevronsRight, CircleDollarSign, CircleEllipsis, CirclePlus, Clock3,
  CreditCard, DatabaseBackup, Download, Expand, Eye, FileSpreadsheet, FileText,
  Globe, Grid, KeyRound, Landmark, Layers, LayoutDashboard, LayoutGrid, ListTree,
  LockKeyhole, LogOut, Mail, Maximize, Menu, Minimize, Monitor, Package, PackagePlus,
  PackageSearch, Pause, Pencil, Plus, Printer, QrCode, ReceiptText, RefreshCw,
  RotateCcw, ScanBarcode, Search, Settings, Shapes, ShieldCheck, ShoppingBag,
  ShoppingCart, Shrink, Smartphone, Sparkles, Store, Tag, Tags, Trash2,
  TrendingDown, TrendingUp, TriangleAlert, Truck, Undo2, UserCheck, UserCog,
  Users, WalletCards, Warehouse, Bell
} from "lucide-react";

const icons = {
  dashboard: LayoutDashboard,
  pos: ShoppingCart,
  monitor: Monitor,
  sales: ReceiptText,
  invoices: FileText,
  print: Printer,
  refund: RotateCcw,
  returns: Undo2,
  export: Download,
  products: Package,
  "create-product": PackagePlus,
  "expired-products": CalendarX,
  "low-stocks": TrendingDown,
  categories: Shapes,
  "sub-category": ListTree,
  brands: Award,
  units: Layers,
  attributes: Tags,
  warranties: ShieldCheck,
  "print-barcode": Barcode,
  "print-qr": QrCode,
  "manage-stock": Warehouse,
  "stock-adjustment": RefreshCw,
  "stock-transfer": Truck,
  inventory: Warehouse,
  purchases: Boxes,
  "purchase-returns": RotateCcw,
  expenses: WalletCards,
  reports: ChartNoAxesCombined,
  users: Users,
  "user-cog": UserCog,
  "admin-role": ShieldCheck,
  key: KeyRound,
  lock: LockKeyhole,
  backups: DatabaseBackup,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  arrow: ArrowRight,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevrons-left": ChevronsLeft,
  "chevrons-right": ChevronsRight,
  trend: TrendingUp,
  profit: TrendingUp,
  refresh: RefreshCw,
  alert: TriangleAlert,
  clock: Clock3,
  check: Check,
  plus: Plus,
  "plus-circle": CirclePlus,
  search: Search,
  edit: Pencil,
  trash: Trash2,
  eye: Eye,
  box: Boxes,
  barcode: ScanBarcode,
  cash: Banknote,
  card: CreditCard,
  bank: Landmark,
  wallet: Smartphone,
  other: CircleEllipsis,
  hold: Pause,
  bell: Bell,
  mail: Mail,
  store: Store,
  globe: Globe,
  maximize: Maximize,
  minimize: Minimize,
  expand: Expand,
  shrink: Shrink,
  "shopping-bag": ShoppingBag,
};

function Icon({ name, className = "size-5", strokeWidth = 1.8 }) {
  const Component = icons[name] || Package;
  return <Component className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}

export default Icon;
