export const settingsSections = [
  {
    key: "shop",
    label: "Shop & branding",
    description: "Identity and receipt contact details",
    fields: [
      ["shop_name", "Shop name", "text"],
      ["address", "Address", "textarea"],
      ["phone", "Phone number", "text"],
      ["email", "Email", "email"],
      ["registration_number", "Tax / registration number", "text"],
      ["default_customer_name", "Default customer name", "text"],
      ["receipt_footer", "Receipt footer", "textarea"],
      ["return_policy", "Return policy", "textarea"],
    ],
  },
  {
    key: "localization",
    label: "Localization",
    description: "Currency, time zone and formats",
    fields: [
      ["currency_code", "Currency code", "text"],
      ["currency_symbol", "Currency symbol", "text"],
      [
        "currency_position",
        "Symbol position",
        "select",
        [
          ["before", "Before amount"],
          ["after", "After amount"],
        ],
      ],
      ["decimal_places", "Decimal places", "number"],
      [
        "thousand_separator",
        "Thousand separator",
        "select",
        [
          [",", "Comma"],
          [".", "Period"],
          [" ", "Space"],
          ["", "None"],
        ],
      ],
      [
        "decimal_separator",
        "Decimal separator",
        "select",
        [
          [".", "Period"],
          [",", "Comma"],
        ],
      ],
      [
        "timezone",
        "Time zone",
        "select",
        [
          ["Asia/Karachi", "Asia / Karachi"],
          ["UTC", "UTC"],
          ["Asia/Dubai", "Asia / Dubai"],
          ["Europe/London", "Europe / London"],
          ["America/New_York", "America / New York"],
        ],
      ],
      [
        "date_format",
        "Date format",
        "select",
        [
          ["d-m-Y", "DD-MM-YYYY"],
          ["m-d-Y", "MM-DD-YYYY"],
          ["Y-m-d", "YYYY-MM-DD"],
          ["d/m/Y", "DD/MM/YYYY"],
        ],
      ],
      [
        "time_format",
        "Time format",
        "select",
        [
          ["12", "12 hour"],
          ["24", "24 hour"],
        ],
      ],
      [
        "first_day_of_week",
        "First day of week",
        "select",
        [
          ["monday", "Monday"],
          ["sunday", "Sunday"],
        ],
      ],
    ],
  },
  {
    key: "tax",
    label: "Tax",
    description: "Trusted sale tax calculation",
    fields: [
      ["enabled", "Enable tax", "toggle"],
      ["name", "Tax label", "text"],
      ["percentage", "Tax percentage", "number"],
      [
        "calculation_mode",
        "Calculation mode",
        "select",
        [
          ["after_discount", "After discount"],
          ["before_discount", "Before discount"],
        ],
      ],
      ["show_on_receipt", "Show tax on receipt", "toggle"],
    ],
  },
  {
    key: "discounts",
    label: "Discounts",
    description: "Default and cashier limits",
    fields: [
      ["enabled", "Enable discounts", "toggle"],
      [
        "default_type",
        "Default type",
        "select",
        [
          ["fixed", "Fixed amount"],
          ["percentage", "Percentage"],
        ],
      ],
      ["default_value", "Default value", "number"],
      ["maximum_cashier_discount", "Cashier maximum (%)", "number"],
      ["allow_cashier_discounts", "Allow cashier discounts", "toggle"],
      ["require_admin_above_limit", "Require admin above limit", "toggle"],
    ],
  },
  {
    key: "inventory",
    label: "Inventory",
    description: "Stock enforcement and alerts",
    fields: [
      ["global_tracking_enabled", "Enable stock tracking globally", "toggle"],
      ["default_minimum_stock", "Default minimum stock", "number"],
      ["allow_negative_stock", "Allow insufficient tracked stock", "toggle"],
      ["low_stock_alerts", "Low stock alerts", "toggle"],
      ["out_of_stock_alerts", "Out of stock alerts", "toggle"],
      ["wastage_tracking", "Wastage tracking", "toggle"],
      ["expiry_tracking", "Expiry tracking", "toggle"],
    ],
  },
  {
    key: "barcode",
    label: "Barcode",
    description: "Scanner behavior in POS",
    fields: [
      ["enabled", "Enable barcode scanning", "toggle"],
      ["auto_focus", "Auto-focus barcode input", "toggle"],
      ["auto_add", "Add matched product automatically", "toggle"],
      ["input_timeout_ms", "Input timeout (ms)", "number"],
    ],
  },
  {
    key: "customers",
    label: "Customers",
    description: "Customer capture in POS",
    fields: [
      ["enabled", "Enable customer details", "toggle"],
      ["use_walk_in", "Use walk-in customer by default", "toggle"],
      ["require_phone", "Require customer phone", "toggle"],
      [
        "save_optional_information",
        "Save optional customer information",
        "toggle",
      ],
    ],
  },
  {
    key: "receipt",
    label: "Receipt",
    description: "Paper and visible sale details",
    fields: [
      [
        "paper_width",
        "Paper width",
        "select",
        [
          ["80mm", "80 mm"],
          ["58mm", "58 mm"],
        ],
      ],
      ["show_phone", "Show phone number", "toggle"],
      ["show_logo", "Show shop logo", "toggle"],
      ["show_customer", "Show customer information", "toggle"],
      ["show_cashier", "Show cashier name", "toggle"],
      ["show_tax", "Show tax", "toggle"],
      ["show_discount", "Show discount", "toggle"],
      ["show_payment_method", "Show payment method", "toggle"],
      ["show_change", "Show returned change", "toggle"],
      ["auto_print", "Open print after sale", "toggle"],
    ],
  },
  {
    key: "printer",
    label: "Printer",
    description: "Local receipt print preferences",
    private: true,
    fields: [
      [
        "printing_method",
        "Printing method",
        "select",
        [
          ["browser", "Browser print"],
          ["qz", "QZ Tray (requires integration)"],
        ],
      ],
      ["printer_name", "Receipt printer name", "text"],
      ["label_printer_name", "Label printer name", "text"],
      ["direct_printing_enabled", "Direct printing", "toggle"],
      ["copies", "Receipt copies", "number"],
    ],
  },
  {
    key: "security",
    label: "Security",
    description: "Session and sensitive actions",
    private: true,
    fields: [
      ["automatic_logout", "Automatic logout", "toggle"],
      ["inactivity_timeout_minutes", "Inactivity timeout (minutes)", "number"],
      [
        "require_password_for_sensitive_actions",
        "Confirm password for sensitive actions",
        "toggle",
      ],
    ],
  },
  {
    key: "backups",
    label: "Backups",
    description: "Preferences for the Backups module",
    private: true,
    fields: [
      ["backup_folder", "Backup folder", "text"],
      ["retention_days", "Retention days", "number"],
      ["automatic_backup", "Automatic backup preference", "toggle"],
      ["automatic_backup_time", "Preferred backup time", "time"],
    ],
  },
  {
    key: "offline",
    label: "Offline Emergency",
    description: "Configure local PIN access & IndexedDB sync",
    private: true,
    fields: [],
  },
];
