import { useEffect, useState } from "react";
import Modal from "../Modal";
function SaleActionDialog({ action, isSubmitting, onClose, onSubmit }) {
  const [reason,setReason]=useState("");const [method,setMethod]=useState("cash");
  useEffect(()=>{setReason("");setMethod("cash");},[action?.sale?.id,action?.type]);
  if(!action)return null;const refund=action.type==="refund";
  function submit(event){event.preventDefault();onSubmit({reason, ...(refund?{refund_method:method}:{})});}
  return <Modal isOpen title={`${refund?"Refund":"Cancel"} ${action.sale.invoice_number}`} description={refund?"This performs a full refund and restores tracked stock.":"This cancels the sale and restores tracked stock."} onClose={isSubmitting?()=>{}:onClose} size="sm"><form onSubmit={submit} className="p-5"><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Reason</span><textarea autoFocus required maxLength="500" value={reason} onChange={(e)=>setReason(e.target.value)} className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100" placeholder="Enter a clear audit reason..."/></label>{refund&&<label className="mt-4 block"><span className="mb-1.5 block text-xs font-bold text-slate-600">Refund method</span><select value={method} onChange={(e)=>setMethod(e.target.value)} className="min-h-10 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="mobile_wallet">Mobile wallet</option><option value="other">Other</option></select></label>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} disabled={isSubmitting} className="rounded-lg border border-slate-200 px-4 py-2.5 text-xs font-bold text-slate-600">Keep sale</button><button type="submit" disabled={isSubmitting||!reason.trim()} className={`rounded-lg px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50 ${refund?"bg-amber-600 hover:bg-amber-700":"bg-red-600 hover:bg-red-700"}`}>{isSubmitting?"Processing...":refund?"Confirm full refund":"Confirm cancellation"}</button></div></form></Modal>;
}
export default SaleActionDialog;
