import Icon from "../Icon";

const inputClass="min-h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700 outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100";
function iso(date){const year=date.getFullYear();const month=String(date.getMonth()+1).padStart(2,"0");const day=String(date.getDate()).padStart(2,"0");return `${year}-${month}-${day}`;}
function SalesFilters({ filters, search, cashiers, onSearch, onChange, onClear }) {
  function preset(type){const now=new Date();let from=new Date(now);if(type==="week"){const day=(now.getDay()+6)%7;from.setDate(now.getDate()-day);}if(type==="month")from=new Date(now.getFullYear(),now.getMonth(),1);onChange({date_from:iso(from),date_to:iso(now),page:1});}
  return <section className="premium-surface rounded-xl p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><Icon name="search" className="absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={(e)=>onSearch(e.target.value)} className={`${inputClass} pl-10`} placeholder="Search invoice, customer, phone or product..."/></label><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>preset("today")} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50">Today</button><button type="button" onClick={()=>preset("week")} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50">This week</button><button type="button" onClick={()=>preset("month")} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-50">This month</button><button type="button" onClick={onClear} className="rounded-lg px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50">Clear filters</button></div></div>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">From</span><input type="date" value={filters.date_from} onChange={(e)=>onChange({date_from:e.target.value,page:1})} className={inputClass}/></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">To</span><input type="date" value={filters.date_to} onChange={(e)=>onChange({date_to:e.target.value,page:1})} className={inputClass}/></label>
  {cashiers.length>0&&<label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Cashier</span><select value={filters.cashier_id} onChange={(e)=>onChange({cashier_id:e.target.value,page:1})} className={inputClass}><option value="">All cashiers</option>{cashiers.map((cashier)=><option key={cashier.id} value={cashier.id}>{cashier.name} · {cashier.role}</option>)}</select></label>}
  <label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Payment</span><select value={filters.payment_method} onChange={(e)=>onChange({payment_method:e.target.value,page:1})} className={inputClass}><option value="">All methods</option><option value="cash">Cash</option><option value="card">Card</option><option value="bank_transfer">Bank transfer</option><option value="mobile_wallet">Mobile wallet</option><option value="other">Other</option></select></label>
  <label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Payment status</span><select value={filters.payment_status} onChange={(e)=>onChange({payment_status:e.target.value,page:1})} className={inputClass}><option value="">All statuses</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></label>
  <label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Sale status</span><select value={filters.status} onChange={(e)=>onChange({status:e.target.value,page:1})} className={inputClass}><option value="">All statuses</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="refunded">Refunded</option></select></label>
  <label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Customer</span><input value={filters.customer} onChange={(e)=>onChange({customer:e.target.value,page:1})} className={inputClass} placeholder="Name or phone"/></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Minimum total</span><input type="number" min="0" step="0.01" value={filters.min_total} onChange={(e)=>onChange({min_total:e.target.value,page:1})} className={inputClass} placeholder="0.00"/></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Maximum total</span><input type="number" min="0" step="0.01" value={filters.max_total} onChange={(e)=>onChange({max_total:e.target.value,page:1})} className={inputClass} placeholder="0.00"/></label><label><span className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Sort by</span><select value={`${filters.sort_by}:${filters.sort_direction}`} onChange={(e)=>{const[sort_by,sort_direction]=e.target.value.split(":");onChange({sort_by,sort_direction,page:1});}} className={inputClass}><option value="created_at:desc">Newest first</option><option value="created_at:asc">Oldest first</option><option value="grand_total:desc">Highest total</option><option value="grand_total:asc">Lowest total</option><option value="invoice_number:asc">Invoice A–Z</option></select></label></div></section>;
}
export default SalesFilters;
